# Generated by Django 5.1.7 on 2025-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=255)),
                ('itemName', models.CharField(max_length=255)),
                ('itemQuantity', models.IntegerField()),
            ],
        ),
    ]
